# Generated by Django 2.1.4 on 2018-12-19 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events_app', '0002_auto_20181218_2236'),
        ('events_app', '0003_foods_brought_by'),
    ]

    operations = [
    ]
