# Generated by Django 2.1.4 on 2018-12-19 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events_app', '0004_merge_20181219_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foods',
            name='brought_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login_app.Users'),
        ),
    ]
