# Generated by Django 2.1.4 on 2018-12-20 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_app', '0005_auto_20181219_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='location',
            field=models.CharField(default='edit this location', max_length=255),
            preserve_default=False,
        ),
    ]
