# Generated by Django 2.1.4 on 2018-12-18 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='group_desc',
            field=models.TextField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
