# Generated by Django 2.1.4 on 2018-12-20 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0001_initial'),
        ('groups_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PMessages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login_app.Users')),
                ('sent_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_to', to='login_app.Users')),
            ],
        ),
        migrations.RemoveField(
            model_name='messages',
            name='groupid',
        ),
        migrations.RemoveField(
            model_name='messages',
            name='posted_by',
        ),
        migrations.DeleteModel(
            name='Messages',
        ),
    ]
