# Generated by Django 2.1.4 on 2018-12-18 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0003_auto_20181218_0830'),
        ('groups_app', '0002_groups_group_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='group_owner',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='login_app.Users'),
            preserve_default=False,
        ),
    ]
