# Generated by Django 2.1.4 on 2018-12-18 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0002_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='taken',
            field=models.BooleanField(default=False),
        ),
    ]
